# Generated by Django 6.0.4 on 2026-05-02 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='factories.factory')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
